export default {
  Vector: require('../assets/images/Vector.png'),
  Frame1744: require('../assets/images/Frame1744.png'),
  Frame1746: require('../assets/images/Frame1746.png'),
  Group22: require('../assets/images/Group22.png'),
  Party64: require('../assets/images/Party64.png'),
  Frame1749: require('../assets/images/Frame1749.png'),
  Peep45: require('../assets/images/Peep45.png'),
  Image6: require('../assets/images/Image(6).png'),
  Image7: require('../assets/images/Image(7).png'),
  Image8: require('../assets/images/Image(8).png'),
  Image9: require('../assets/images/Image(9).png'),
  Image10: require('../assets/images/Image(10).png'),
  Image11: require('../assets/images/Image(11).png'),
  Image13: require('../assets/images/Image(13).png'),
};
